"""Mensaje descriptivo de la migración

Revision ID: 1ddfd09c4275
Revises: 
Create Date: 2025-11-29 12:07:04.190577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddfd09c4275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('letra', sa.String(length=1), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facultades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=False),
    sa.Column('directorio', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('codigopostal', sa.String(length=10), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('domicilio', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipodocumentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('libreta_civica', sa.String(length=20), nullable=False),
    sa.Column('libreta_enrolamiento', sa.String(length=20), nullable=False),
    sa.Column('pasaporte', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('libreta_civica'),
    sa.UniqueConstraint('libreta_enrolamiento'),
    sa.UniqueConstraint('pasaporte')
    )
    op.create_table('tipoespecialidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('nrodocumento', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('nro_legajo', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipodocumentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumnos')
    op.drop_table('universidad')
    op.drop_table('tipoespecialidades')
    op.drop_table('tipodocumentos')
    op.drop_table('grados')
    op.drop_table('facultades')
    op.drop_table('especialidades')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
