"""Inicial

Revision ID: 54b750a7250e
Revises: 
Create Date: 2025-12-03 09:53:40.189121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b750a7250e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facultades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=False),
    sa.Column('directorio', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('codigopostal', sa.String(length=10), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('domicilio', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('universidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['universidad_id'], ['universidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('letra', sa.String(length=1), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('facultad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('especialidades')
    op.drop_table('facultades')
    op.drop_table('universidades')
    # ### end Alembic commands ###
